# Generated by Django 3.0.2 on 2020-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, '学校区'), (2, '学院区'), (3, '专业区'), (4, '表白墙')], default=None),
        ),
    ]
