# Generated by Django 3.0.2 on 2020-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_action_menu_permission_permission2action_permission2action2role_role_user_user2role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
